[versions]

[libraries]
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-annotation = "androidx.annotation:annotation:1.3.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-livedata = "androidx.lifecycle:lifecycle-livedata-ktx:2.4.1"
androidx-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.1"
androidx-test-junit = "androidx.test.ext:junit:1.1.3"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.4.0"
google-material = "com.google.android.material:material:1.6.1"
junit = "junit:junit:4.13.2"

[plugins]
android="com.android.application:7.3.0-beta05"
kotlin="org.jetbrains.kotlin.android:1.7.0"
