[versions]
kotlin = "1.7.0"
agp = "7.3.0-beta05"
androidx-lifecycle = "2.4.1"

[libraries]
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-annotation = "androidx.annotation:annotation:1.3.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-test-junit = "androidx.test.ext:junit:1.1.3"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.4.0"
google-material = "com.google.android.material:material:1.6.1"
junit = "junit:junit:4.13.2"

[plugins]
android = { id = "com.android.application", version.ref = "agp" }
android-lib = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
